#!/bin/bash

TOKEN=$(cat ./token | sed -E 's|[\\s]+||gi')
echo -ne "TOKEN: '${TOKEN}'\n"

export GITHUB_ACCESS_TOKEN="${TOKEN}"

if [[ "$1" == "list" ]]; then
	echo 'calling list.sh'
	./bin/list.sh $2 $3
	exit $?
fi

if [[ "$1" == "create" ]]; then
	echo 'Calling create.sh'
	./bin/create.sh $2 $3 $4 $5
	exit $?
fi
