#!/bin/bash

function help(){
	echo 'Usage: ./runner <SCRIPT> <param-1>...[param-N]'
	echo 
	echo 'List of scripts:'
	echo 'list <USER> <REPO>'       
	echo '  - will list releases belonging to USER+REPO'
	echo 
	echo 'create <USER> <REPO> <TAG> <NAME_OF_RELEASE>'
	echo '  - will create a release using TAG and NAME_OF_RELEASE as the name'
	echo '    - tag must already exist for this to work!'
	echo 
	echo 'list-release-assets <USER> <REPO> <RELEASE_ID>'
	echo '  - gets the list of assets for a specific release'
	echo 
	echo 'upload-release-asset <USER> <REPO> <RELEASE_ID> <PATH_TO_FILE> <NAME_OF_ASSET>'
	echo '  - Uploads a .zip file at PATH_TO_FILE and adds that to the release specified by RELEASE_ID'
	echo
	echo 'upload-targz-release-asset <USER> <REPO> <RELEASE_ID> <PATH_TO_FILE> <NAME_OF_ASSET>'
	echo '  - Uploads a .tar.gz file at PATH_TO_FILE and adds that to the release specified by RELEASE_ID'
	echo
	echo
}
if [[ $# -lt 2 ]]; then
	help
	exit 1
fi

if [[ "$1" == "-h" || "$1" == "--help" || "$1" == "--usage" || "$1" == "help" ]]; then
	help
	exit 1
fi

TOKEN=$(cat ./token | sed -E 's|[\\s]+||gi')

export GITHUB_ACCESS_TOKEN="${TOKEN}"

if [[ "$1" == "list" ]]; then
	echo 'calling list.sh'
	./bin/list.sh $2 $3
	exit $?
fi

if [[ "$1" == "create" ]]; then
	echo 'Calling create.sh'
	./bin/create.sh $2 $3 $4 $5
	exit $?
fi

if [[ "$1" == "list-release-assets" ]]; then
	echo 'Calling list-release-assets.sh'
	./bin/list-release-assets.sh $2 $3 $4
	exit $?
fi

if [[ "$1" == "upload-release-asset" ]]; then
	echo 'Calling upload-release-asset.sh'
	./bin/upload-release-asset.sh $2 $3 $4 $5 $6
	exit $?
fi

if [[ "$1" == "upload-targz-release-asset" ]]; then
	echo 'Calling upload-targz-release-asset.sh'
	./bin/upload-targz-release-asset.sh $2 $3 $4 $5 $6
	exit $?
fi

echo 'Uh-oh, we didnt run any scripts. Perhaps you should take a look at the help screen'
help
exit 1
